---
name: PART3 - CH1 - Function 1
on: 
  issues:
    types: [opened, edited, labeled, unlabeled]
jobs:
    build:
      runs-on: ubuntu-latest
      if: ${{ contains(github.event.issue.labels.*.name, 'bug') }}
      steps:
      - name: Auto assign issue
        uses: actions-cool/issues-helper@v1.11
        with:
          assignees: ${{ vars.BUG_HUNTERS }}
