---
name: PART3 - CH4 - AWS OIDC Credentials 
on: workflow_dispatch
jobs:
  s3:
    name: S3 Upload using OIDC Credentials
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::909622006439:role/GitHubActionTestRole
        role-duration-seconds: 600
    - name: Generate File
      run: |
        echo "Workflow: ${{ github.GITHUB_WORKFLOW }} | Build ID: ${{ github.run_id }}" > build.txt
    - name: Upload File to AWS S3
      run: |
        aws s3 sync ./build.txt s3://${{ secrets.S3_BUCKET }}/build.txt
    - name: Notice when a build finishes
      if: always()
      uses: 8398a7/action-slack@v3.2.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        status: ${{job.status}}
        fields: repo,message,workflow,job,ref
        author_name: Github Action Slack