---
name: PART3 - CH4 - Github Secrets for Slack
on: workflow_dispatch
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Build project
      run: |
        echo "Build Project"
    - name: Run tests
      run: |
        echo "Run Test"
    - name: Notice when a build fails
      if: failure()
      uses: 8398a7/action-slack@v3.2.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        status: ${{job.status}}
        fields: repo,message,workflow,job, author
        author_name: Github Action Slack
    - name: Notice when a build succeeds
      if: success()
      uses: 8398a7/action-slack@v3.2.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
          status: ${{job.status}}
          fields: repo,message,workflow,job
          author_name: Github Action Slack
          message: Success to Deploy on ${{ env.K8S_NAMESPACE }} (${{ env.GCP_ARTIFACT_REGISTRY_REPO }}:${{ env.TAG }})
          color: good