name: PART4 - CH1 - Contents exposed from untrused input
on: 
  issues:
    types: [opened, edited]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Move Sample code
        run: |
          mv secret_sample/my_secret.json ./
          mv secret_sample/secret_passphrase ./
      - name: Check Issue Title
        run: |
          title="${{ github.event.issue.title }}"
          echo $title
