---
  name: PART3 - CH4 - Google Cloud Service Account Key 
  on: workflow_dispatch
  jobs:
    s3:
      name: Google Cloud Storage Upload using Service Account Key
      runs-on: ubuntu-latest
      permissions:
        id-token: write
        contents: read
      steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Retrieve the Service Account Key and decode it to a file
        run: |
          echo ${{ secrets.GOOGLE_CREDENTIALS }} | base64 --decode > $HOME/gcloud-service-key.json
      - name: Generate File
        run: |
          echo "Build ID: ${{ github.run_id }}" auth through Google Cloud Credential Key > ./build.txt
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v0.3.1'
        with:
          credentials_json: gcloud-service-key.json
      - name: Upload File to Google Cloud Storage
        run: |
          gsutil cp ./build.txt gs://githubaction-test-001/build.txt
      - name: Notice when a build finishes
        if: always()
        uses: 8398a7/action-slack@v3.2.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{job.status}}
          fields: repo,message,workflow,job,ref
          author_name: Github Action Slack