name: PART5 - CH2 - CI (Java with Gradle)
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Move Java Sample code
      run: |
        mv build_sample/java/* ./
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.3'
    - name: Build with Gradle
      run: ./gradlew build

    