name: PART3 - CH1 - Sample
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout 
          uses: actions/checkout@v2
        - name: Build project
          run: |
            echo "Build Project"
        - name: Run tests
          run: |
            echo "Run Test"
    deploy:
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
        - name: Deploy to production
          run: |
            echo "Deploying to production server"
            
