name: PART5 - CH4 - CI (Python)

on: 
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version'
        required: true
        default: '3.8'
        type: choice
        options:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
jobs:
  pypi-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Move Python Sample code
        run: |
          mv build_sample/python/* ./
      - name: "Set up Python ${{ github.event.inputs.python-version }}"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ github.event.inputs.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Setup Build
        run: |
          python setup.py sdist bdist_wheel
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@27b1fca
        with:
          user: ${{ secrets.PYPI_USERNAME }}}
          password: ${{ secrets.PYPI_PASSWORD }}
          repository_url: https://upload.pypi.org/legacy/
          build_dir: dist